### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by localjo** [Magyartanulas/magyartanulas.github.io#24]
I think [this translation](https://github.com/Magyartanulas/magyartanulas.github.io/blame/master/dative_possession.md#L274) isn't quite right in English. Shouldn't the sentence "Tegnap kutyákat láttunk a parkban, lehet, hogy miattuk vannak ott azok a lyukak" be translated "Yesterday we saw dogs in the park, it's possible that due to them those holes are there" instead of "Yesterday we saw holes in the park, this could be due to those dogs there."?

De nem éppen jó a magyarom, lehet, hogy tévedek. :)

**Comment by Mirlington** [comment]
Nice spotting!

The translation is now: `Yesterday we saw dogs in the park. It's possible that those holes are there due to them.`

I've broken up the compound sentence to make it sound more natural in English.
